# Generated by Django 5.1.3 on 2024-11-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Item_Product',
        ),
    ]
