# Generated by Django 5.1.3 on 2024-11-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_rename_unit_of_meature_unit_of_measure_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='enter_date',
            field=models.DateField(auto_now=True, verbose_name='วันที่บันทึก'),
        ),
    ]
